"""
HLS Router

Serves HLS playlist (.m3u8) and segment (.ts) files generated by FFmpeg.
Mobile clients use these endpoints to play hardware-decoded live video
via expo-video's native HLS support.

Endpoints:
    GET /api/v1/hls/{room_id}/playlist.m3u8  — HLS playlist
    GET /api/v1/hls/{room_id}/{filename}      — .ts segment files
    GET /api/v1/hls/status                     — active stream info
"""

import os

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

from app.config import settings, logger
from app.services.hls_service import hls_service

router = APIRouter()


@router.get("/{room_id}/playlist.m3u8")
async def get_playlist(room_id: str):
    """Serve the HLS playlist for a room."""
    segment_dir = hls_service.get_segment_dir(room_id)
    playlist_path = os.path.join(segment_dir, "playlist.m3u8")

    if not os.path.exists(playlist_path):
        raise HTTPException(status_code=404, detail="Playlist not found — stream may not be active")

    return FileResponse(
        playlist_path,
        media_type="application/vnd.apple.mpegurl",
        headers={"Cache-Control": "no-cache, no-store, must-revalidate"},
    )


@router.get("/{room_id}/{filename}")
async def get_segment(room_id: str, filename: str):
    """Serve an HLS .ts segment file."""
    # Prevent directory traversal
    if ".." in filename or "/" in filename or "\\" in filename:
        raise HTTPException(status_code=400, detail="Invalid filename")

    segment_dir = hls_service.get_segment_dir(room_id)
    file_path = os.path.join(segment_dir, filename)

    if not os.path.exists(file_path):
        raise HTTPException(status_code=404, detail="Segment not found")

    # Determine media type
    if filename.endswith(".ts") or filename.endswith(".m4s"):
        media_type = "video/mp2t"
    elif filename.endswith(".mp4"):
        media_type = "video/mp4"
    elif filename.endswith(".m3u8"):
        media_type = "application/vnd.apple.mpegurl"
    else:
        media_type = "application/octet-stream"

    return FileResponse(
        file_path,
        media_type=media_type,
        headers={"Cache-Control": "max-age=1"},
    )


@router.get("/status")
async def hls_status():
    """Get HLS streaming system status."""
    active_rooms = hls_service.get_active_rooms()
    rooms = [
        {
            "room_id": rid,
            "viewers": hls_service.get_viewer_count(rid),
        }
        for rid in active_rooms
    ]

    return {
        "success": True,
        "data": {
            "active_streams": len(active_rooms),
            "rooms": rooms,
            "hls_segment_duration": settings.HLS_SEGMENT_DURATION,
            "hls_playlist_size": settings.HLS_PLAYLIST_SIZE,
        },
    }
